sre_dashboard/sre_dashboard/base_app/urls.py
from django.urls import path
from base_app import views

app_name = 'base_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('issue-dashboard', views.IssueDashboardView.as_view(), name='issue-dashboard'),
    path('issue-sla-report', views.IssueSLAReportView.as_view(), name='issue-sla-report'),
    path('issue-sla-update', views.IssueSLAUpdateView.as_view(), name='issue-sla-update'),
    path('app-mon-list', views.AllAppMonStatus.as_view(), name='app-mon-list'),
    path('<str:app_id>/app-detail/', views.AppMonDetailView.as_view(), name='app-detail'),
    path('app-mon-add/', views.AppMonAddView.as_view(), name='app-mon-add'),
    path('app-mon-update/<str:pk>', views.AppMonUpdateView.as_view(), name='app-mon-update'),
    path('sli-add/', views.SLIAddView.as_view(), name='sli-add'),
]

sre_dashboard/sre_dashboard/sre_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls', namespace='base_app')),
]

sre_dashboard/sre_dashboard/base_app/models.py
from django.db import models
from django.utils import timezone

class IssuePriority(models.Model):
    name = models.CharField(max_length=128, primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "issue_priority"
        ordering = ['name']


class IssueLabels(models.Model):
    name = models.CharField(max_length=128, primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "issue_labels"        
        ordering = ['name']


class Issues(models.Model):
    key = models.CharField(max_length=128, primary_key=True)
    project_name = models.CharField(max_length=128, null=True, blank=True)
    project_key = models.CharField(max_length=128, null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    priority = models.ForeignKey('IssuePriority', related_name='priority_issue', null=True, on_delete=models.SET_NULL)
    labels = models.ManyToManyField('IssueLabels', related_name='label_issue')
    assignee_display_name = models.CharField(max_length=256, null=True, blank=True)
    # assignee_email_address = models.EmailField(max_length=254, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    status_name = models.CharField(max_length=64, null=True, blank=True)
    description = models.CharField(max_length=4068, null=True, blank=True)
    summary = models.CharField(max_length=1024, null=True, blank=True)
    creator_display_name = models.CharField(max_length=256, null=True, blank=True)
    # creator_email_address = models.EmailField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.key

    class Meta:
        db_table = "issues"
        ordering = ['-created']

    @property
    def workMinutes(self):
        "Minutes ticket from ticket opened and last updated"
        if self.status_name == 'Done':  # If ticket is closed take the last updated time
            time_delta = self.updated - self.created
        else:            # If ticket is under work the take the time difference from now
            time_delta = timezone.now() - self.created
        return int(time_delta.seconds/60)

    @property
    def isInSLA(self):
        "Is ticket under SLA"
        sla_metric = IssueSLA.objects.get(priority=self.priority)
        return sla_metric.minutes > self.workMinutes
        

class IssueSLA(models.Model):
    # priority = models.ForeignKey('IssuePriority', related_name='priority_sla', null=True, on_delete=models.SET_NULL)
    priority = models.OneToOneField('IssuePriority', related_name='priority_sla', on_delete=models.CASCADE)
    minutes = models.PositiveIntegerField(default=1440)            # Minutes

    def __str__(self):
        return f"{self.priority.name}: {self.minutes}"

    class Meta:
        db_table = "issue_sla"
        ordering = ['minutes']


APP_STATUS_CHOICES = (
        ('yellow', 'YELLOW'),
        ('green', 'GREEN'),
        ('red', 'RED'),
    )


class AppMon(models.Model):
    name = models.CharField(max_length=64)
    status = models.CharField(max_length=8, default='green', choices=APP_STATUS_CHOICES)
    slis = models.ManyToManyField('AppMonSLI', blank=True, related_name='sli_app')

    class Meta:
        db_table = "app_mon"
        ordering = ['name']

    def __str__(self):
        return self.name


SLI_EXPRESSION_CHOICES = (
        ('<', '<'),
        ('>', '>'),
        ('=', '='),
        ('!=', '!='),
        ('<=', '<='),
        ('>=', '>='),
    )

class AppMonSLI(models.Model):
    name = models.CharField(max_length=128)
    query = models.CharField(max_length=1024)
    threshold = models.FloatField(default=0.0)
    expression = models.CharField(max_length=8, default='<', choices=SLI_EXPRESSION_CHOICES)
    data_points = models.ManyToManyField('AppMonSLIData', blank=True, related_name='sli')
    is_threshold_breached = models.BooleanField(default=False)

    class Meta:
        db_table = "mon_sli"
        ordering = ['name']

    def __str__(self):
        return self.name


class AppMonSLIData(models.Model):
    value = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "sli_data"
        ordering = ['-created_at']   # Reverse ordering for time series

    def __str__(self):
        return str(self.created_at.timestamp())

sre_dashboard/sre_dashboard/base_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.db.models import Count
# from django_pandas.io import read_frame
from base_app.models import Issues, IssueSLA, IssueLabels, IssuePriority,\
                         AppMon, AppMonSLI
from plotly.offline import plot
from plotly.graph_objs import Scatter
import plotly.graph_objects as go

PLOTLY_DEFAULT_CONFIG = {        
                            "displaylogo": False, 
                            'modeBarButtonsToRemove': ['pan2d', 'lasso2d'],
                            'toImageButtonOptions': {'filename': "Overall_Report"}
                        }

def get_plot_object(fig):
    return plot(
                fig,
                output_type = 'div', 
                config = PLOTLY_DEFAULT_CONFIG,
                include_plotlyjs=False
        )

class Index(TemplateView):
    """ Default Landing Page """
    template_name = 'base_app/base_app_index.html'


class IssueSLAReportView(TemplateView):
    """ All Issue Dashboard """
    template_name = 'base_app/base_app_issue_sla_report.html'

    def get_context_data(self, **kwargs):
        context = super(IssueSLAReportView, self).get_context_data(**kwargs)
        context['issue_list'] = Issues.objects.all()
        context['issue_sla_list'] = IssueSLA.objects.all()
        return context


class IssueDashboardView(TemplateView):
    """ All Issue Dashboard """
    template_name = 'base_app/base_app_issue_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(IssueDashboardView, self).get_context_data(**kwargs)
        issue_list = Issues.objects.all()

        # Label Stats
        issue_count_by_labels = IssueLabels.objects.all()\
                                .values('name')\
                                .annotate(total=Count('label_issue'))\
                                .order_by('-total')\
        
        tmp_dict = { obj['name']:obj['total'] for obj in issue_count_by_labels }
        # Plot for Issue count by Label
        data = []
        data.append(go.Bar(x=list(tmp_dict.keys()), 
                    y=list(tmp_dict.values()),
                    marker = {'color' : 'royalblue'}
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig = go.Figure(data=data, layout=layout)
        fig.update_xaxes(title_text='Labels', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Labels</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_label_plot_div = get_plot_object(fig)
        context['issue_count_by_label_plot_div'] = issue_count_by_label_plot_div


        
        # Priority Stats
        issue_count_by_priority = IssuePriority.objects.all()\
                                    .values('name')\
                                    .annotate(total=Count('priority_issue'))\
                                    .order_by('-total')
        tmp_dict = { obj['name']:obj['total'] for obj in issue_count_by_priority }
        # Plot for Issue count by Priority
        data = []
        data.append(go.Bar(x=list(tmp_dict.keys()), 
                    y=list(tmp_dict.values()),
                    marker = {'color' : 'royalblue'}
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig = go.Figure(data=data, layout=layout)
        fig.update_xaxes(title_text='Priority', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Priority</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_priority_plot_div = get_plot_object(fig)
        context['issue_count_by_priority_plot_div'] = issue_count_by_priority_plot_div

        
        # Assignee Stats
        issue_count_by_assignee = Issues.objects.all()\
                                    .values('assignee_display_name')\
                                    .annotate(total=Count('assignee_display_name'))\
                                    .order_by('-total')
        tmp_dict = { obj['assignee_display_name']:obj['total'] for obj in issue_count_by_assignee }
        # Plot for Issue count by Assignee
        data = []
        data.append(go.Bar(x=list(tmp_dict.keys()), 
                    y=list(tmp_dict.values()),
                    marker = {'color' : 'royalblue'}
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig = go.Figure(data=data, layout=layout)
        fig.update_xaxes(title_text='Assignee', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Assignee</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_assignee_plot_div = get_plot_object(fig)
        context['issue_count_by_assignee_plot_div'] = issue_count_by_assignee_plot_div

        # Issues by Day
        fig = go.Figure(layout=layout)
        # issues_list = Issues.objects.values('created__date').annotate(count=Count('pk')).values('created__date', 'count').order_by('created__date')
        tmp_list = issue_list.values('created__date').annotate(count=Count('pk')).values('created__date', 'count').order_by('created__date')
        tmp_dict = { obj['created__date']:obj['count'] for obj in tmp_list }
        fig.add_trace(
                        go.Scatter(
                                    x=list(tmp_dict.keys()), 
                                    y=list(tmp_dict.values()), 
                                    fillcolor='royalblue',
                                    fill='tozeroy',
                                    mode='none' # override default markers+lines
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig.update_xaxes(title_text='Day', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Date</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_date_plot_div = get_plot_object(fig)
        context['issue_count_by_date_plot_div'] = issue_count_by_date_plot_div

        # Issues by Month
        fig = go.Figure(layout=layout)
        tmp_list = issue_list.values('created__date__month').annotate(count=Count('pk')).values('created__date__month', 'count').order_by('created__date__month')
        tmp_dict = { obj['created__date__month']:obj['count'] for obj in tmp_list }
        fig.add_trace(
                        go.Scatter(
                                    x=list(tmp_dict.keys()), 
                                    y=list(tmp_dict.values()), 
                                    fillcolor='royalblue',
                                    fill='tozeroy',
                                    mode='none' # override default markers+lines
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig.update_xaxes(title_text='Month', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Month</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_month_plot_div = get_plot_object(fig)
        context['issue_count_by_month_plot_div'] = issue_count_by_month_plot_div

        # Issues by Year
        fig = go.Figure(layout=layout)
        tmp_list = issue_list.values('created__date__year').annotate(count=Count('pk')).values('created__date__year', 'count').order_by('created__date__year')
        tmp_dict = { obj['created__date__year']:obj['count'] for obj in tmp_list }
        data = []
        data.append(go.Bar(x=list(tmp_dict.keys()), 
                    y=list(tmp_dict.values()),
                    marker = {'color' : 'royalblue'}
                    ))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig = go.Figure(data=data, layout=layout)
        fig.update_xaxes(title_text='Year', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>Issue Count by Year</b>")
        fig.update_layout(width=400, height=400)
        issue_count_by_year_plot_div = get_plot_object(fig)
        context['issue_count_by_year_plot_div'] = issue_count_by_year_plot_div

        # SLA Breakup
        tmp_dict = {'In SLA': 0, 'Out Of SLA': 0}
        for issue in issue_list:
            if issue.isInSLA:
               tmp_dict['In SLA'] += 1
            else:
               tmp_dict['Out Of SLA'] += 1

        labels = list(tmp_dict.keys())
        values = list(tmp_dict.values())
        data = []
        data.append(go.Pie(labels=labels, values=values))
        layout = go.Layout(barmode='group', paper_bgcolor="ghostwhite")
        fig = go.Figure(data=data, layout=layout)
        fig.update_xaxes(title_text='Priority', showline=True, linewidth=2, linecolor='black')
        fig.update_yaxes(title_text='Count', showline=True, linewidth=2, linecolor='black')
        fig.update_layout(title_text="<b>SLA Breakup</b>")
        fig.update_layout(width=400, height=400)
        issue_sla_breakup_plot_div = get_plot_object(fig)
        context['issue_sla_breakup_plot_div'] = issue_sla_breakup_plot_div

        return context



class IssueSLAUpdateView(CreateView):
    """ Form to update the Jira ticket SLAs """
    model = IssueSLA

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_appmon_add.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <hr>
    <div class="box">
        <section class="section">
            <form method="post">
                {% csrf_token %}
                <div class="field">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    <div class="control">
                            {{ form.name }}
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                    <button class="button is-small is-info is-rounded" type="submit" value="Submit">Submit</button>
                    <a class="button is-small is-info is-rounded" href="{% url 'base_app:index' %}">Cancel</a>
                    </div>
                </div>
            </form>
        </section>        
    </div>
</div>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_appmon_app_update.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<style>
    input {
        width: 30%;
    }
    #id_slis {
        width: 60%;
    }
</style> 
<div class="container">
    <hr>
    <h5 class="title is-5">Update</h5>
    <h6 class="subtitle is-6">Update app name and sli(s)</h6>
    <hr>
    <div class="box">
        <section class="section">
            <form method="post">
                {% csrf_token %}
                <div class="field">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    <div class="control">
                            {{ form.name }}
                    </div>
                </div>
                <div class="field">
                    <label for="{{ form.slis.id_for_label }}">{{ form.slis.label }}</label>
                    <div class="control">
                            {{ form.slis }}
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                    <button class="button is-small is-info is-rounded" type="submit" value="Submit">Submit</button>
                    <a class="button is-small is-info is-rounded" href="{% url 'base_app:app-mon-list' %}">Cancel</a>
                    </div>
                </div>
            </form>
        </section>        
    </div>
</div>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_appmon_detail.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <hr>
    <h5 class="title is-5">App Status</h5>
    <h6 class="subtitle is-6">SLI details and status</h6>
    <hr>
    <div class="box">
        <section class="section">
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="5" 
                            {% if app.status == "green" %}
                                style="background-color: rgb(166, 241, 136); text-align: center;"
                            {% elif app.status == "yellow" %}
                                style="background-color: rgb(245, 247, 148); text-align: center;"
                            {% else %}
                                style="background-color: rgb(230, 122, 122); text-align: center;"
                            {% endif %}
                        >
                        {{ app.name }}</th>
                    </tr>
                    <tr>
                        <th>SLI</th>
                        <th>Query</th>
                        <th>Threshold</th>
                        <!-- <th>Expression</th> -->                        
                        <th>Last Value</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sli in app.slis.all %}
                    <tr>
                        <td>{{ sli.name }}</td>
                        <td>{{ sli.query }}</td>
                        <td>{{ sli.threshold }}</td>
                        <!-- <td>{{ sli.expression }}</td>  -->                   
                        <td 
                            {% if sli.is_threshold_breached %}
                                style="background-color: rgb(236, 117, 117);"
                            {% else %}
                                style="background-color: rgb(194, 236, 117);"
                            {% endif %}
                        >
                            {{ sli.data_points.all.first.value }}
                        </td>
                        <td>
                            {{ sli.data_points.all.first.created_at|date:"d/m/Y" }} {{ sli.data_points.all.first.created_at|time:"H:i" }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a class="button is-small is-link is-rounded" href="{% url 'base_app:app-mon-list' %}">App List</a>
        </section>        
    </div> <!-- box -->
    <div class="box">
        {% autoescape off %}
        {{ sli_by_date_plot_div }}
        {% endautoescape %}        
    </div>    
</div>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_appmon_report.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <hr>
    <h5 class="title is-5">Apps</h5>
    <h6 class="subtitle is-6">All tracked apps</h6>
    <hr>
    <div class="box">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>SLI Count</th>
                    <th>Status</th>
                    <th></th>                    
                </tr>
            </thead>
            <tbody>
                {% for app in app_list %}
                <tr>
                    <td><a href="{% url 'base_app:app-detail' app_id=app.pk %}"">{{ app.name }}</a></td>
                    <td>{{ app.slis.all | length }}</td>
                    <td
                        {% if app.status == "green" %}
                            style="background-color: rgb(166, 241, 136); text-align: center;"
                        {% elif app.status == "yellow" %}
                            style="background-color: rgb(245, 247, 148); text-align: center;"
                        {% else %}
                            style="background-color: rgb(230, 122, 122); text-align: center;"
                        {% endif %}
                    ></td>
                    <td>
                        <a class="button is-small is-info is-rounded" href="{% url 'base_app:app-mon-update' pk=app.pk %}">Update SLIs</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_appmon_sli_add.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<style>
    input {
        width: 30%;
      }
    #id_query {
        width: 80%;
    }
</style>

<div class="container">
    <hr>
    <h5 class="title is-5">Add SLI</h5>
    <h6 class="subtitle is-6">Add SLI and associate it to App</h6>
    <hr>
    <div class="box">
        <section class="section">
            <form method="post">
                {% csrf_token %}
                <div class="field">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    <div class="control">
                            {{ form.name }}
                    </div>
                </div>
                <div class="field">
                    <label for="{{ form.query.id_for_label }}">{{ form.query.label }}</label>
                    <div class="control">
                            {{ form.query }}
                    </div>
                </div>
                <div class="field">
                    <label for="{{ form.expression.id_for_label }}">{{ form.expression.label }}</label>
                    <div class="control">
                            {{ form.expression }}
                    </div>
                </div>
                <div class="field">
                    <label for="{{ form.threshold.id_for_label }}">{{ form.threshold.label }}</label>
                    <div class="control">
                            {{ form.threshold }}
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                    <button class="button is-small is-info is-rounded" type="submit" value="Submit">Submit</button>
                    <a class="button is-small is-info is-rounded" href="{% url 'base_app:app-mon-list' %}">Cancel</a>
                    </div>
                </div>
            </form>
        </section>        
    </div>
</div>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_base.html
<html>
    <head>
        {% load static %}
        {# load django_simple_bulma #}
        {# bulma #}
        {# font_awesome #}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
        <script src="https://cdn.plot.ly/plotly-2.16.1.min.js"></script>
        {% block extra_js %}
        {% endblock %}
        </head>
        <body>
            {# Navbar #}
            <nav class="navbar is-dark">
                <div class="navbar-brand">

                    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
        
                <div id="navbarExampleTransparentExample" class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="{% url 'base_app:index' %}">
                            Home
                        </a>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <!-- <a class="navbar-link" href="/documentation/overview/start/"> -->
                            <a class="navbar-link">
                                Tickets
                            </a>
                            <div class="navbar-dropdown is-boxed">
                                <a class="navbar-item" href="{% url 'base_app:issue-sla-report' %}">
                                    Issue SLA Report
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:issue-sla-update' %}">
                                    Issue SLA Update
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:issue-dashboard' %}">
                                    Issue Dashboard
                                </a>
                            </div>
                        </div>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <!-- <a class="navbar-link" href="/documentation/overview/start/"> -->
                            <a class="navbar-link">
                                Monitoring
                            </a>
                            <div class="navbar-dropdown is-boxed">
                                <a class="navbar-item" href="{% url 'base_app:app-mon-list' %}">
                                    App List
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:app-mon-add' %}">
                                    Add App
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:sli-add' %}">
                                    Add SLI
                                </a>
                            </div>
                        </div>
                    </div>
        
                    <div class="navbar-end">
                    </div>
                </div>
            </nav>
            {# Block to place page content #}
            {% block body_block %}
            {% endblock %}
        </body>
</html>

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_index.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
    <section class="hero is-medium is-link" style="background: linear-gradient(-30deg, #243a5eE5, #243a5eE5 50%, #243a5e 45%) #fff;">
        <div class="hero-body has-text-centered">
            <p class="title">
                SRE Dashboard
            </p>
        </div>
    </section>

    <section class="section">
        
        </div>
    </section>
{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_issue_dashboard.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}

<div class='container'>
    <hr>
    <h5 class="title is-5">SLA Dashboard</h5>
    <h6 class="subtitle is-6">Work insights</h6>
    <hr>
    <table>
        <tbody>
            <tr>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_label_plot_div }}
                    {% endautoescape %}
                </td>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_priority_plot_div }}
                    {% endautoescape %}
                </td>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_assignee_plot_div }}
                    {% endautoescape %}
                </td>
            </tr>
            <tr>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_date_plot_div }}
                    {% endautoescape %}                    
                </td>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_month_plot_div }}
                    {% endautoescape %}                    
                </td>
                <td>
                    {% autoescape off %}
                    {{ issue_count_by_year_plot_div }}
                    {% endautoescape %}                    
                </td>
            </tr>
            <tr>
                <td>
                    {% autoescape off %}
                    {{ issue_sla_breakup_plot_div }}
                    {% endautoescape %}                    
                </td>
            </tr>
        </tbody>
</div>

{% endblock %}

sre_dashboard/sre_dashboard/base_app/templates/base_app/base_app_sla_update_form.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <hr>
    <div class="box">
        <section class="section">
            <form method="post">
                {% csrf_token %}
                <div class="field">
                    <label for="{{ form.priority.id_for_label }}">{{ form.priority.label }}</label>
                    <div class="control">
                            {{ form.priority }}
                    </div>
                </div>
                <div class="field">
                    <label for="{{ form.minutes.id_for_label }}">{{ form.minutes.label }}</label>
                    <div class="control">
                            {{ form.minutes }}
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-small is-info is-rounded" type="submit" value="Submit">Submit</button>
                        <a class="button is-small is-info is-rounded"  href="{% url 'base_app:index' %}">Cancel</a>
                    </div>
                </div>
            </form>    
        </section>        
    </div>
</div>
{% endblock %}